# Generated by Django 2.1.3 on 2018-11-18 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_pizza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['price'], 'verbose_name': 'Пиццария', 'verbose_name_plural': 'Пиццарии'},
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizzaShop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.PizzaShop', verbose_name='Name of store'),
        ),
    ]
